import Link from "next/link";
import { ArrowRight, ExternalLink, Lightbulb, Radar, Sparkles } from "lucide-react";
import { EventCard } from "@/components/event-card";
import { Badge } from "@/components/ui/badge";
import { getLatestBriefing } from "@/lib/content";

function koreanDate(value: string) {
  return new Intl.DateTimeFormat("ko-KR", { year: "numeric", month: "long", day: "numeric", weekday: "long", timeZone: "Asia/Seoul" }).format(new Date(`${value}T00:00:00+09:00`));
}

export default async function TodayPage() {
  const briefing = await getLatestBriefing();
  if (!briefing) return <main className="mx-auto min-h-[60vh] max-w-6xl px-4 py-20 sm:px-6 lg:px-8"><h1 className="text-3xl font-black">아직 공개된 브리핑이 없습니다.</h1></main>;
  return <main>
    <section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-4 py-9 sm:px-6 sm:py-11 lg:px-8"><div className="flex flex-wrap items-center gap-2 text-[11px] font-bold tracking-[0.1em] text-blue-700"><Sparkles className="size-3.5" aria-hidden />오늘 · {koreanDate(briefing.dateKst)}</div><div className="mt-4 grid gap-5 lg:grid-cols-[1fr_17rem] lg:items-end"><div><p className="mb-2 text-xs font-bold text-slate-500">TODAY&apos;S INSIGHT</p><h1 className="max-w-4xl text-balance text-[1.7rem] font-black leading-[1.28] tracking-[-0.035em] sm:text-[2rem] lg:text-[2.25rem]">{briefing.todaysInsight}</h1></div><p className="border-l-2 border-blue-500 pl-3 text-xs leading-5 text-slate-600">출처와 검증 상태를 함께 읽는 사건 중심 AI 브리핑입니다.</p></div>{briefing.status === "partial" && <div role="status" className="mt-5 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-900">일부 항목의 수집 또는 검증이 진행 중입니다. 확인된 내용은 먼저 공개합니다.</div>}</div></section>

    <div className="mx-auto grid max-w-6xl gap-8 px-4 py-8 sm:px-6 lg:grid-cols-[minmax(0,1fr)_20rem] lg:px-8"><section aria-labelledby="top-news"><div className="mb-1 flex items-center justify-between"><div><p className="section-kicker">THE BRIEF</p><h2 id="top-news" className="section-title">오늘의 핵심 뉴스</h2></div><Badge>{briefing.events.length} EVENTS</Badge></div>{briefing.events.slice(0, 5).map((event, index) => <EventCard key={event.id} event={event} rank={index + 1} />)}</section>
      <aside className="space-y-5"><section className="rounded-xl border border-slate-200 bg-slate-950 p-5 text-white"><Radar className="size-5 text-blue-400" aria-hidden /><p className="mt-4 text-[10px] font-bold tracking-[0.12em] text-blue-300">OPPORTUNITY RADAR</p><h2 className="mt-1 text-xl font-black">실행 가능한 사업 기회</h2><div className="mt-4 space-y-4">{briefing.opportunities.slice(0, 3).map((idea) => <article key={idea.id} className="border-t border-white/15 pt-4 first:border-0 first:pt-0"><div className="flex justify-between gap-3"><h3 className="text-sm font-bold">{idea.name}</h3><span className="text-xs font-bold text-blue-300">{idea.score.toFixed(1)}</span></div><p className="mt-1.5 line-clamp-3 text-xs leading-5 text-slate-300">{idea.problem}</p></article>)}</div><Link href="/opportunities" className="mt-5 flex items-center justify-center gap-1 rounded-md bg-blue-600 px-3 py-2 text-xs font-bold hover:bg-blue-500">전체 기회 보기<ArrowRight className="size-3.5" aria-hidden /></Link></section>
        <section className="rounded-xl border border-slate-200 bg-white p-5"><p className="section-kicker"><Lightbulb className="mr-1.5 inline size-3.5" aria-hidden />TRENDING SIGNALS</p><div className="mt-3 space-y-4">{briefing.trends.slice(0, 4).map((trend) => <article key={trend.id} className="border-t border-slate-100 pt-3 first:border-0 first:pt-0"><div className="flex items-center justify-between gap-3"><h3 className="text-xs font-bold">{trend.label}</h3>{trend.mood && <span className="text-[10px] text-slate-500">{trend.mood}</span>}</div><p className="mt-1.5 text-xs leading-5 text-slate-600">{trend.summary}</p></article>)}</div><Link href="/trends" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-blue-700">7일·30일 흐름 보기<ArrowRight className="size-3.5" aria-hidden /></Link></section></aside>
    </div>

    <section id="resources" className="scroll-mt-16 border-t border-slate-200 bg-slate-50/60"><div className="mx-auto max-w-6xl px-4 py-9 sm:px-6 lg:px-8"><p className="section-kicker">TOOLS · OPEN SOURCE · PAPERS</p><h2 className="section-title">도구와 더 읽을 자료</h2><div className="mt-5 divide-y divide-slate-200 overflow-hidden rounded-lg border border-slate-200 bg-white">{briefing.resources.map((resource) => <a key={resource.id} href={resource.url} target="_blank" rel="noopener noreferrer" className="group grid gap-2 px-4 py-3 hover:bg-blue-50/60 sm:grid-cols-[6rem_minmax(0,1fr)_2fr_auto] sm:items-center"><Badge>{resource.type}</Badge><h3 className="text-sm font-bold group-hover:text-blue-700">{resource.title}</h3><p className="text-xs leading-5 text-slate-600">{resource.whyRelevant}</p><ExternalLink className="size-3.5 text-slate-400" aria-hidden /></a>)}</div></div></section>
  </main>;
}
